export function safeNextPath(raw: string | null | undefined, fallback = "/dashboard"): string {
  if (!raw) return fallback;
  if (!raw.startsWith("/") || raw.startsWith("//") || raw.includes("://")) return fallback;
  return raw;
}

export type PublicPactProfile = {
  pact: {
    id: string;
    title: string;
    slug: string;
    description: string | null;
    category: string;
    frequencyType: string;
    targetCountPerWeek: number;
    checkInStartTime: string;
    checkInEndTime: string;
    startDate: string;
    endDate: string | null;
    createdAt: string;
    noJudgementZone: boolean;
  };
  owner: {
    id: string;
    username: string;
    displayName: string;
    tagline: string | null;
    profileMode: string;
  };
  stats: {
    memberCount: number;
    daysLive: number;
    successRate: number;
    avgCompletionPercentage: number;
    totalCheckIns: number;
    activeThisWeek: number;
    topStreak: number;
  };
  leaders: Array<{
    displayName: string;
    currentStreak: number;
    completionPercentage: number;
  }>;
};

export type PublicPactListItem = {
  id: string;
  title: string;
  slug: string;
  description: string | null;
  category: string;
  memberCount: number;
  daysLive: number;
  successRate: number;
  avgCompletionPercentage: number;
  noJudgementZone: boolean;
  createdAt: string;
};

export type PublicPactPostItem = {
  id: string;
  body: string;
  createdAt: string;
  author: { displayName: string };
};

const API_URL = process.env.NEXT_PUBLIC_API_URL || "http://localhost:4000";

export function siteUrl(): string {
  return (process.env.NEXT_PUBLIC_SITE_URL || "http://localhost:3000").replace(/\/$/, "");
}

export function siteFeedUrl(): string {
  return `${siteUrl()}/feed.xml`;
}

export function exploreFeedUrl(): string {
  return `${siteUrl()}/explore/feed.xml`;
}

export function pactFeedUrl(slug: string): string {
  return `${siteUrl()}/p/${encodeURIComponent(slug)}/feed.xml`;
}

export async function fetchPublicPact(slug: string): Promise<PublicPactProfile | null> {
  const res = await fetch(`${API_URL}/public/pacts/${encodeURIComponent(slug)}`, {
    // Avoid serving a stale incomplete payload after API shape changes in local/dev.
    cache: "no-store",
  });
  if (res.status === 404) return null;
  if (!res.ok) throw new Error("Failed to load public pact");
  const data = (await res.json()) as PublicPactProfile;
  if (!data?.pact?.id || !data?.owner?.id) return null;
  return data;
}

export async function fetchPublicPactList(): Promise<PublicPactListItem[]> {
  const res = await fetch(`${API_URL}/public/pacts`, {
    next: { revalidate: 60 },
  });
  if (!res.ok) throw new Error("Failed to load public pacts");
  const data = (await res.json()) as { pacts: PublicPactListItem[] };
  return data.pacts;
}

export async function fetchPublicPactPosts(
  slug: string
): Promise<{ pact: { id: string; title: string; slug: string }; posts: PublicPactPostItem[] } | null> {
  const res = await fetch(`${API_URL}/public/pacts/${encodeURIComponent(slug)}/posts`, {
    next: { revalidate: 60 },
  });
  if (res.status === 404) return null;
  if (!res.ok) throw new Error("Failed to load public pact posts");
  return res.json();
}

export function publicPactShareUrl(slug: string): string {
  const site = process.env.NEXT_PUBLIC_SITE_URL || "http://localhost:3000";
  return `${site.replace(/\/$/, "")}/p/${slug}`;
}

/** Absolute URL for the cached Open Graph PNG (generated by `pnpm og:pacts`). */
export function publicPactOgImageUrl(slug: string): string {
  const api = process.env.NEXT_PUBLIC_API_URL || "http://localhost:4000";
  return `${api.replace(/\/$/, "")}/uploads/og/pacts/${encodeURIComponent(slug)}.png`;
}

export function formatCategory(category: string): string {
  return category
    .toLowerCase()
    .split("_")
    .map((part) => part.charAt(0).toUpperCase() + part.slice(1))
    .join(" ");
}
