import { StyleSheet } from "react-native";

export const colors = {
  navy: "#0f1729",
  navyLight: "#1a2744",
  gold: "#d4a853",
  goldLight: "#e8c97a",
  cream: "#f5f0e6",
  sage: "#5a8f7b",
  muted: "#94a3b8",
  white: "#ffffff",
};

export const styles = StyleSheet.create({
  container: { flex: 1, backgroundColor: colors.cream },
  screen: { flex: 1, padding: 20, backgroundColor: colors.cream },
  title: { fontSize: 28, fontWeight: "700", color: colors.navy, marginBottom: 8 },
  subtitle: { fontSize: 16, color: colors.muted, marginBottom: 20 },
  card: {
    backgroundColor: colors.white,
    borderRadius: 16,
    padding: 16,
    marginBottom: 12,
    borderWidth: 1,
    borderColor: "rgba(15,23,41,0.1)",
  },
  input: {
    backgroundColor: colors.white,
    borderWidth: 1,
    borderColor: "rgba(15,23,41,0.15)",
    borderRadius: 12,
    padding: 14,
    marginBottom: 12,
    fontSize: 16,
    color: colors.navy,
  },
  btnPrimary: {
    backgroundColor: colors.gold,
    borderRadius: 12,
    padding: 16,
    alignItems: "center",
  },
  btnPrimaryText: { color: colors.navy, fontWeight: "700", fontSize: 16 },
  btnSecondary: {
    borderWidth: 1,
    borderColor: "rgba(15,23,41,0.2)",
    borderRadius: 12,
    padding: 14,
    alignItems: "center",
    marginTop: 8,
  },
  btnSecondaryText: { color: colors.navy, fontWeight: "600" },
  badge: {
    alignSelf: "flex-start",
    backgroundColor: "rgba(15,23,41,0.05)",
    paddingHorizontal: 10,
    paddingVertical: 4,
    borderRadius: 20,
    fontSize: 11,
    color: colors.muted,
    overflow: "hidden",
  },
  streak: { color: colors.gold, fontWeight: "700" },
  link: { color: colors.gold, fontWeight: "600" },
  header: {
    backgroundColor: colors.navy,
    paddingHorizontal: 20,
    paddingVertical: 16,
    flexDirection: "row",
    justifyContent: "space-between",
    alignItems: "center",
  },
  headerTitle: { color: colors.gold, fontSize: 20, fontWeight: "700" },
  headerLink: { color: colors.cream, fontSize: 14 },
});
